language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - ./create_config.sh
script:
  - npm test
after_success:
  - node lib/run.js --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET}
env:
  global:
    - secure: frX1/0ApfjBVuNWIwZzztO8+gX4kc6rH1E/UzDqwlcf9cpIT7Jc2MbZ+bDqxirW5IxEpgyl0TBH5JHMTvtHhlBfKTfd57EgJ+8IkNJb61nrCfxDQnEsWPcQ7Fd38qCyplZAIdUjoWPDLtlYbm05fRHhMNNc6w2epTW0L3ixyFs0=
    - secure: C7sUPZAA79hvt++/afEPbsiiKdroBdQiYnQ4/GEByBkBmAs5bCMyRGiNrQBGZXEkhGlSm9sfimvnAmvjHU6UBgzRVuOesLw2j5seteVptHz1Res0m2o2Rlzp4HnFSJ4qNq8KySmHMyDKIH5p3FUeI/9lyepAFP0lR0y4POdh0t8=
    - secure: aeG5BTXx57MueyG4AzvH1tE5ea/Sp4n9tV3cg0+VobclUqNvv0rmUoJNNUtbi6LA3zMzza0/Cn18blaxxGqBuv5ubJMnF+YE2y8bfBwBO2SzLlRq2Cg6HerRk0HUPz5DRtKAy37ocK+4GNh0S7hscxaeaCYeRvA12e2aaca23Zo=
notifications:
  hipchat:
    rooms:
      - secure: sl29cxk+oGen2lXoQcyyk+4T70snQShB3njksOml9q0iZ79F4BcDo87hx8/l+lbNDfj68i0uI1AOfK8YAotM3gzhfULtKLAJDNIRacg1d1DxE67VVt+v9m5rpcE40lG46nsxv1LVzHbVN1exxAyNNXWRl+ZEYgagiPjHfaRUF68=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a> <a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
