language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- ./create_config.sh
after_success:
- node lib/run.js --projectKey ${SPHERE_PROJECT_KEY} --clientId ${SPHERE_CLIENT_ID} --clientSecret ${SPHERE_CLIENT_SECRET}
env:
  global:
  - secure: UlCxfamCW8+iT2/lAfficJqOHPXDTCtvSDcVkrA4PkWdMMKFSNq3K8WGr4mwD9rJX4RvBC0+52vKa3JbpZeW3z+QqzrPZgrhW1H5nZeI75nGcvUL0wm77uUT0rO/cW4u4Zt+Y3VqHSvnEbaUIUK3hePVwR44AHev5OroaovEnzo=
  - secure: pYTH7TjK9FGPMJIVzmAKIevtlrAasny3WyzASlxsqgbCsIs2sP0ISri2XdgTlJVOArO4xB+EW4hyOr7yv+dSRr2ArffL06u/s9kv3y0NDKwTk9NBWK5a5FM69yfU8Sy/oi1hcynF3R7ndy05H1fasDJrmWO0ZGBkb8l8gk/yKqw=
  - secure: Xke2BDxR4DGyYGQFhKsBWrIbQRFvrW/fnQMVyMHVK1ajJAFEvBeNtIJEGeUgdWG4sUgSXqDZRfYQaA7nVDk3YEOQcavr+J2zaYvfNDCpZH55RLFvJdj1kDEoisXQ/NjOpPbKWV7gosttBBudi7vq+CUyfPDimg9fTnlclxZn+sg=
